"""Build the compact Classic estimate lookup from Questie Forever v27.

Usage: python tools/import_questie_drops.py path/to/Questie-Forever-beta-patch-v27.zip
Without an argument, rebuilds from the included Data/Source files.
Only parses numeric table entries; never executes downloaded Lua.
"""
import hashlib
import json
from pathlib import Path
import re
import sys
from zipfile import ZipFile
from import_wowhead_drops import merge_records

ROOT = Path(__file__).resolve().parents[1]
SHA256 = "70218f96f71a9172b1c1184b333b76ec387840715b52745e9e75b500a0f01e11"
PREFIX = "Questie/Database/DropTables/data/"


def parse_table(body, names):
    result = {}
    item = None
    for raw in body.splitlines():
        line = raw.split("--", 1)[0].strip()
        if not line or line in ("return {", "{", "}", "}]]"):
            continue
        start = re.fullmatch(r"\[(\d+)\]\s*=\s*\{", line)
        if start:
            item = int(start[1])
            result[item] = {}
            if "--" in raw:
                names.setdefault(item, raw.split("--", 1)[1].strip())
            continue
        if line == "},":
            item = None
            continue
        entry = re.fullmatch(r"\[(\d+)\]\s*=\s*([\d.]+|DropKeys\.WOWHEAD|DropKeys\.PSERVER),?", line)
        if not entry or item is None:
            raise ValueError(f"Unrecognized table row: {raw}")
        value = entry[2]
        result[item][int(entry[1])] = value if value.startswith("DropKeys") else float(value)
    return result


def main(path=None):
    source = ROOT / "Data/Source"
    if path:
        path = Path(path)
        if hashlib.sha256(path.read_bytes()).hexdigest() != SHA256:
            raise ValueError("Source archive does not match the reviewed Questie Forever v27 file")
        source.mkdir(parents=True, exist_ok=True)
        with ZipFile(path) as archive:
            for name in ("classicItemDrops.lua", "itemDropCorrections.lua"):
                (source / name).write_bytes(archive.read(PREFIX + name))
    data = (source / "classicItemDrops.lua").read_text(encoding="utf-8-sig")
    corrections = (source / "itemDropCorrections.lua").read_text(encoding="utf-8-sig")
    names = {}
    tables = {}
    for key in ("wowheadData", "cmangosData"):
        body = re.search(r"QuestieClassicItemDrops\." + key + r"\s*=\s*\[\[(.*?)\]\]", data, re.S)[1]
        tables[key] = parse_table(body, names)
    body = corrections.split("QuestieItemDropCorrections.Era =", 1)[1].split("QuestieItemDropCorrections.Tbc =", 1)[0]
    corrections = parse_table(body, names)
    wowhead, cmangos = tables["wowheadData"], tables["cmangosData"]
    npcs = {}
    used_items = set()
    for item in sorted(wowhead.keys() | cmangos.keys() | corrections.keys()):
        wh, cm, fix = wowhead.get(item, {}), cmangos.get(item, {}), corrections.get(item, {})
        for npc in sorted(wh.keys() | cm.keys() | fix.keys()):
            rate = fix.get(npc)
            if rate == "DropKeys.WOWHEAD":
                rate = wh.get(npc)
            elif rate == "DropKeys.PSERVER":
                rate = cm.get(npc)
            if rate is None:
                rate = cm.get(npc, wh.get(npc))
            if rate is not None and 0 < rate <= 100 and item in names:
                npcs.setdefault(npc, {})[item] = rate
                used_items.add(item)
    supplement = source / 'wowheadForeverDrops.json'
    if supplement.exists():
        snapshot = json.loads(supplement.read_text(encoding='utf-8'))
        if snapshot.get('schema') != 1:
            raise ValueError('Unsupported Forever observation schema')
        merge_records(snapshot['items'], npcs, names)
        used_items = {item for items in npcs.values() for item in items}
    lines = ["-- Generated by tools/import_questie_drops.py; do not hand-edit.",
             "-- Questie Classic estimates plus Wowhead Forever observations; see Data/NOTICE.md.",
             "-- Derived database: GPL-3.0; see Data/NOTICE.md and Data/COPYING.txt.",
             "BetaQoLQuestDrops = { names = {"]
    for item in sorted(used_items):
        lines.append(f"[{item}]={json.dumps(names[item], ensure_ascii=False)},")
    lines.append("}, npcs = {")
    for npc, items in sorted(npcs.items()):
        values = ",".join(f"[{item}]={rate:g}" for item, rate in sorted(items.items()))
        lines.append(f"[{npc}]={{{values}}},")
    lines.append("} }")
    out = ROOT / "Data/QuestItemDrops.lua"
    out.parent.mkdir(exist_ok=True)
    out.write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
    print(f"Built {len(npcs)} NPCs, {len(used_items)} items, {sum(map(len, npcs.values()))} pairs; {out.stat().st_size} bytes")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
